spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_batch_fetch_size: 20
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nts
    username: root
    password: 1234

cors:
  allowedOrigins:
    - http://localhost:3000
    - http://127.0.0.1:3000